"""Whole-score MusicXML validation and CLaMP embedding pipeline."""

from .clamp_extractor import (
    ClampModelIdentity,
    ClampRuntimeConfig,
    EmbeddingBatch,
    TextEmbeddingBatch,
    check_clamp3_setup,
    embed_clamp3_texts,
    load_and_normalize_embeddings,
    run_clamp3_extraction,
    setup_clamp3,
)
from .music_processing import (
    ConversionReport,
    ConversionStatus,
    NoteEvent,
    ScoreConversionResult,
    StandardizationConfig,
    process_score_to_xml,
    standardize_score,
)
from .mei_metadata import ScoreCatalogMetadata, extract_mei_catalog_metadata
from .pipeline import (
    MeiAggregateManifest,
    PipelineConfig,
    PipelineRunResult,
    ScoreInput,
    ScoreRunResult,
    SkippedInput,
    classify_mei_aggregate,
    discover_mei_inputs,
    query_similar,
    run_pipeline,
)
from .storage import (
    CatalogEmbedding,
    CatalogSimilarityResult,
    EmbeddingModelIdentity,
    EmbeddingRecord,
    EmbeddingRepository,
    SimilarityResult,
    StoredEmbedding,
)

__all__ = [
    "ClampRuntimeConfig",
    "CatalogEmbedding",
    "CatalogSimilarityResult",
    "ClampModelIdentity",
    "ConversionReport",
    "ConversionStatus",
    "EmbeddingBatch",
    "EmbeddingModelIdentity",
    "EmbeddingRecord",
    "EmbeddingRepository",
    "TextEmbeddingBatch",
    "NoteEvent",
    "MeiAggregateManifest",
    "PipelineConfig",
    "PipelineRunResult",
    "ScoreConversionResult",
    "ScoreCatalogMetadata",
    "ScoreInput",
    "ScoreRunResult",
    "SkippedInput",
    "SimilarityResult",
    "StandardizationConfig",
    "StoredEmbedding",
    "check_clamp3_setup",
    "classify_mei_aggregate",
    "discover_mei_inputs",
    "extract_mei_catalog_metadata",
    "embed_clamp3_texts",
    "load_and_normalize_embeddings",
    "process_score_to_xml",
    "query_similar",
    "run_clamp3_extraction",
    "run_pipeline",
    "setup_clamp3",
    "standardize_score",
]
